import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import {Header} from '@/components/core/Header'

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
}

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body
                className={
                    inter.className +
                    ' bg-gradient-to-b from-bg-gradient-from to-bg-gradient-to min-h-screen text-white'
                }
            >
                <main className="p-4 max-w-2xl mx-auto">
                    <Header />
                    {children}
                </main>
            </body>
        </html>
    )
}
